# Site settings
name: Shamsee Comic
author: Tristan J. Tarwater & Adrian Ricker
email: 

keywords: webcomic, comic, fantasy, comedy, slice of life, Shamsee
description: A weekly fantasy comic about Shamsee and the thieves, rogues, and mischief he finds in the Valley of Ten Crescents.

baseurl: 
url: https://www.shamseecomic.com
unencrypted: http://www.shamseecomic.com
#url: http://localhost:4000

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

#gems:
#  - jekyll-sitemap #updating to Jekyll 3.0 made this plugin stop working

# Compress our Css
sass:
    style: :compressed

permalink: /:categories/:title/

# Set this to false to prevent Jekyll from building pages with a future date.
future: false


# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page
#################################################
####CUSTOM

# Set default header image
header: no
header_sm: images/banner-small.jpg
header_med: images/banner-med.jpg
header_large: images/banner-large.jpg
header_xl: images/banner-xl.jpg

## Thumbnailer taken from https://github.com/chrisanthropic/jekyll-minimagick

# Autogenerate thumbs for comics
mini_magick:

#Create Thumbs for the Archive Page
    thumbnail:
      source: images/comics/
      destination: /images/comics/thumbs
      resize: "182x280^"

#Autogenerate smaller size for small screens       
    small:
      source: images/comics/
      destination: /images/comics/small
      resize: "350x535^"

#Thumbs for fanart
    fanart:
      source: images/fanart/
      destination: /images/fanart/thumbs
      resize: "224x280^"
      
#### SEO Stuff
# Google Analytics
google_universal_analytics: UA-53303028-1
google_universal_analytics_cookiedomain: auto

# Facebook Custom Audience Tracking Pixel
fb_tracking_pixel: 1381762635484775

# Facebook Opengraph
facebook_user: BackThatElfUp
facebook_app_id: 212934732101925                      #enter your App ID
facebook_locale: en_US
facebook_page: https://www.facebook.com/BackThatElfUp                       #the URL of your Facebook Page
facebook_image: https://www.shamseecomic.com/images/SHAM-logo.jpg #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: backthatelfup
twitter_card: true
twitter_image: https://www.shamseecomic.com/images/SHAM-logo.jpg  #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
